import { AdvisorListRelationFilter } from "../advisor/AdvisorListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { AreaListRelationFilter } from "../area/AreaListRelationFilter";
import { AwardListRelationFilter } from "../award/AwardListRelationFilter";
import { CommitteeServiceListRelationFilter } from "../committeeService/CommitteeServiceListRelationFilter";
import { DegreeStatusListRelationFilter } from "../degreeStatus/DegreeStatusListRelationFilter";
import { EmploymentListRelationFilter } from "../employment/EmploymentListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { EvaluationLetterListRelationFilter } from "../evaluationLetter/EvaluationLetterListRelationFilter";
import { ExpNeuroReqListRelationFilter } from "../expNeuroReq/ExpNeuroReqListRelationFilter";
import { FellowshipListRelationFilter } from "../fellowship/FellowshipListRelationFilter";
import { FundingListRelationFilter } from "../funding/FundingListRelationFilter";
import { GeneralDatumListRelationFilter } from "../generalDatum/GeneralDatumListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { InternshipListRelationFilter } from "../internship/InternshipListRelationFilter";
import { InternshipsCdListRelationFilter } from "../internshipsCd/InternshipsCdListRelationFilter";
import { InternshipsIniListRelationFilter } from "../internshipsIni/InternshipsIniListRelationFilter";
import { InternshipsIsrmListRelationFilter } from "../internshipsIsrm/InternshipsIsrmListRelationFilter";
import { InterviewListRelationFilter } from "../interview/InterviewListRelationFilter";
import { ItaListRelationFilter } from "../ita/ItaListRelationFilter";
import { LegacyRequirementListRelationFilter } from "../legacyRequirement/LegacyRequirementListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { NoteListRelationFilter } from "../note/NoteListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { PracticumListRelationFilter } from "../practicum/PracticumListRelationFilter";
import { PresentationListRelationFilter } from "../presentation/PresentationListRelationFilter";
import { ProgramStatusListRelationFilter } from "../programStatus/ProgramStatusListRelationFilter";
import { ProjectTopicListRelationFilter } from "../projectTopic/ProjectTopicListRelationFilter";
import { QualsCommitteeListRelationFilter } from "../qualsCommittee/QualsCommitteeListRelationFilter";
import { RotationListRelationFilter } from "../rotation/RotationListRelationFilter";
import { StatementListRelationFilter } from "../statement/StatementListRelationFilter";
import { StudentAdvisorListRelationFilter } from "../studentAdvisor/StudentAdvisorListRelationFilter";
import { StudentAppListRelationFilter } from "../studentApp/StudentAppListRelationFilter";
import { StudentDataHciiListRelationFilter } from "../studentDataHcii/StudentDataHciiListRelationFilter";
import { StudentDataIniListRelationFilter } from "../studentDataIni/StudentDataIniListRelationFilter";
import { StudentDataMlListRelationFilter } from "../studentDataMl/StudentDataMlListRelationFilter";
import { StudentDataRiWhereUniqueInput } from "../studentDataRi/StudentDataRiWhereUniqueInput";
import { StudentFileListRelationFilter } from "../studentFile/StudentFileListRelationFilter";
import { StudentInstituteListRelationFilter } from "../studentInstitute/StudentInstituteListRelationFilter";
import { StudentMentorListRelationFilter } from "../studentMentor/StudentMentorListRelationFilter";
import { StudentOverrideListRelationFilter } from "../studentOverride/StudentOverrideListRelationFilter";
import { StudentPubListRelationFilter } from "../studentPub/StudentPubListRelationFilter";
import { StudentResidencyListRelationFilter } from "../studentResidency/StudentResidencyListRelationFilter";
import { StudentSkillListRelationFilter } from "../studentSkill/StudentSkillListRelationFilter";
import { TeachingReqListRelationFilter } from "../teachingReq/TeachingReqListRelationFilter";
import { ThesisCommitteeListRelationFilter } from "../thesisCommittee/ThesisCommitteeListRelationFilter";
import { ThesisTopicListRelationFilter } from "../thesisTopic/ThesisTopicListRelationFilter";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

export type StudentDatumWhereInput = {
  advisors?: AdvisorListRelationFilter;
  area?: StringNullableFilter;
  areas?: AreaListRelationFilter;
  awards?: AwardListRelationFilter;
  citizenship?: StringNullableFilter;
  committeeService?: CommitteeServiceListRelationFilter;
  curriculum?: StringNullableFilter;
  degree?: StringNullableFilter;
  degreeStatus?: DegreeStatusListRelationFilter;
  department?: StringNullableFilter;
  employment?: EmploymentListRelationFilter;
  enterDate?: DateTimeNullableFilter;
  evaluationLetters?: EvaluationLetterListRelationFilter;
  expNeuroReq?: ExpNeuroReqListRelationFilter;
  fellowships?: FellowshipListRelationFilter;
  funding?: FundingListRelationFilter;
  gender?: StringNullableFilter;
  generalData?: GeneralDatumListRelationFilter;
  guid?: StringNullableFilter;
  id?: IntFilter;
  institutesId?: StringNullableFilter;
  institutesName?: StringNullableFilter;
  internships?: InternshipListRelationFilter;
  internshipsCds?: InternshipsCdListRelationFilter;
  internshipsIni?: InternshipsIniListRelationFilter;
  internshipsIsrms?: InternshipsIsrmListRelationFilter;
  interview?: InterviewListRelationFilter;
  ita?: ItaListRelationFilter;
  legacyRequirements?: LegacyRequirementListRelationFilter;
  mltSwitch?: BooleanNullableFilter;
  notes?: NoteListRelationFilter;
  parttime?: IntNullableFilter;
  practicum?: PracticumListRelationFilter;
  presentations?: PresentationListRelationFilter;
  program?: StringNullableFilter;
  programStatus?: ProgramStatusListRelationFilter;
  projectTopic?: ProjectTopicListRelationFilter;
  qualsCommittee?: QualsCommitteeListRelationFilter;
  residency?: StringNullableFilter;
  rotations?: RotationListRelationFilter;
  statements?: StatementListRelationFilter;
  status?: StringNullableFilter;
  statusDate?: DateTimeNullableFilter;
  studentAdvisors?: StudentAdvisorListRelationFilter;
  studentApps?: StudentAppListRelationFilter;
  studentDataHcii?: StudentDataHciiListRelationFilter;
  studentDataIni?: StudentDataIniListRelationFilter;
  studentDataMl?: StudentDataMlListRelationFilter;
  studentDataRi?: StudentDataRiWhereUniqueInput;
  studentFiles?: StudentFileListRelationFilter;
  studentInstitutes?: StudentInstituteListRelationFilter;
  studentMentors?: StudentMentorListRelationFilter;
  studentOverrides?: StudentOverrideListRelationFilter;
  studentPubs?: StudentPubListRelationFilter;
  studentResidency?: StudentResidencyListRelationFilter;
  studentSkills?: StudentSkillListRelationFilter;
  teachingReq?: TeachingReqListRelationFilter;
  thesisCommittee?: ThesisCommitteeListRelationFilter;
  thesisTopic?: ThesisTopicListRelationFilter;
  undergrad?: StringNullableFilter;
  userRole?: UserRoleWhereUniqueInput;
  year?: FloatNullableFilter;
  yearAdjust?: StringNullableFilter;
};
