import { AdvisorUpdateManyWithoutStudentDataInput } from "./AdvisorUpdateManyWithoutStudentDataInput";
import { AreaUpdateManyWithoutStudentDataInput } from "./AreaUpdateManyWithoutStudentDataInput";
import { AwardUpdateManyWithoutStudentDataInput } from "./AwardUpdateManyWithoutStudentDataInput";
import { CommitteeServiceUpdateManyWithoutStudentDataInput } from "./CommitteeServiceUpdateManyWithoutStudentDataInput";
import { DegreeStatusUpdateManyWithoutStudentDataInput } from "./DegreeStatusUpdateManyWithoutStudentDataInput";
import { EmploymentUpdateManyWithoutStudentDataInput } from "./EmploymentUpdateManyWithoutStudentDataInput";
import { EvaluationLetterUpdateManyWithoutStudentDataInput } from "./EvaluationLetterUpdateManyWithoutStudentDataInput";
import { ExpNeuroReqUpdateManyWithoutStudentDataInput } from "./ExpNeuroReqUpdateManyWithoutStudentDataInput";
import { FellowshipUpdateManyWithoutStudentDataInput } from "./FellowshipUpdateManyWithoutStudentDataInput";
import { FundingUpdateManyWithoutStudentDataInput } from "./FundingUpdateManyWithoutStudentDataInput";
import { GeneralDatumUpdateManyWithoutStudentDataInput } from "./GeneralDatumUpdateManyWithoutStudentDataInput";
import { InternshipUpdateManyWithoutStudentDataInput } from "./InternshipUpdateManyWithoutStudentDataInput";
import { InternshipsCdUpdateManyWithoutStudentDataInput } from "./InternshipsCdUpdateManyWithoutStudentDataInput";
import { InternshipsIniUpdateManyWithoutStudentDataInput } from "./InternshipsIniUpdateManyWithoutStudentDataInput";
import { InternshipsIsrmUpdateManyWithoutStudentDataInput } from "./InternshipsIsrmUpdateManyWithoutStudentDataInput";
import { InterviewUpdateManyWithoutStudentDataInput } from "./InterviewUpdateManyWithoutStudentDataInput";
import { ItaUpdateManyWithoutStudentDataInput } from "./ItaUpdateManyWithoutStudentDataInput";
import { LegacyRequirementUpdateManyWithoutStudentDataInput } from "./LegacyRequirementUpdateManyWithoutStudentDataInput";
import { NoteUpdateManyWithoutStudentDataInput } from "./NoteUpdateManyWithoutStudentDataInput";
import { PracticumUpdateManyWithoutStudentDataInput } from "./PracticumUpdateManyWithoutStudentDataInput";
import { PresentationUpdateManyWithoutStudentDataInput } from "./PresentationUpdateManyWithoutStudentDataInput";
import { ProgramStatusUpdateManyWithoutStudentDataInput } from "./ProgramStatusUpdateManyWithoutStudentDataInput";
import { ProjectTopicUpdateManyWithoutStudentDataInput } from "./ProjectTopicUpdateManyWithoutStudentDataInput";
import { QualsCommitteeUpdateManyWithoutStudentDataInput } from "./QualsCommitteeUpdateManyWithoutStudentDataInput";
import { RotationUpdateManyWithoutStudentDataInput } from "./RotationUpdateManyWithoutStudentDataInput";
import { StatementUpdateManyWithoutStudentDataInput } from "./StatementUpdateManyWithoutStudentDataInput";
import { StudentAdvisorUpdateManyWithoutStudentDataInput } from "./StudentAdvisorUpdateManyWithoutStudentDataInput";
import { StudentAppUpdateManyWithoutStudentDataInput } from "./StudentAppUpdateManyWithoutStudentDataInput";
import { StudentDataHciiUpdateManyWithoutStudentDataInput } from "./StudentDataHciiUpdateManyWithoutStudentDataInput";
import { StudentDataIniUpdateManyWithoutStudentDataInput } from "./StudentDataIniUpdateManyWithoutStudentDataInput";
import { StudentDataMlUpdateManyWithoutStudentDataInput } from "./StudentDataMlUpdateManyWithoutStudentDataInput";
import { StudentDataRiWhereUniqueInput } from "../studentDataRi/StudentDataRiWhereUniqueInput";
import { StudentFileUpdateManyWithoutStudentDataInput } from "./StudentFileUpdateManyWithoutStudentDataInput";
import { StudentInstituteUpdateManyWithoutStudentDataInput } from "./StudentInstituteUpdateManyWithoutStudentDataInput";
import { StudentMentorUpdateManyWithoutStudentDataInput } from "./StudentMentorUpdateManyWithoutStudentDataInput";
import { StudentOverrideUpdateManyWithoutStudentDataInput } from "./StudentOverrideUpdateManyWithoutStudentDataInput";
import { StudentPubUpdateManyWithoutStudentDataInput } from "./StudentPubUpdateManyWithoutStudentDataInput";
import { StudentResidencyUpdateManyWithoutStudentDataInput } from "./StudentResidencyUpdateManyWithoutStudentDataInput";
import { StudentSkillUpdateManyWithoutStudentDataInput } from "./StudentSkillUpdateManyWithoutStudentDataInput";
import { TeachingReqUpdateManyWithoutStudentDataInput } from "./TeachingReqUpdateManyWithoutStudentDataInput";
import { ThesisCommitteeUpdateManyWithoutStudentDataInput } from "./ThesisCommitteeUpdateManyWithoutStudentDataInput";
import { ThesisTopicUpdateManyWithoutStudentDataInput } from "./ThesisTopicUpdateManyWithoutStudentDataInput";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";

export type StudentDatumUpdateInput = {
  advisors?: AdvisorUpdateManyWithoutStudentDataInput;
  area?: string | null;
  areas?: AreaUpdateManyWithoutStudentDataInput;
  awards?: AwardUpdateManyWithoutStudentDataInput;
  citizenship?: string | null;
  committeeService?: CommitteeServiceUpdateManyWithoutStudentDataInput;
  curriculum?: string | null;
  degree?: string | null;
  degreeStatus?: DegreeStatusUpdateManyWithoutStudentDataInput;
  department?: string | null;
  employment?: EmploymentUpdateManyWithoutStudentDataInput;
  enterDate?: Date | null;
  evaluationLetters?: EvaluationLetterUpdateManyWithoutStudentDataInput;
  expNeuroReq?: ExpNeuroReqUpdateManyWithoutStudentDataInput;
  fellowships?: FellowshipUpdateManyWithoutStudentDataInput;
  funding?: FundingUpdateManyWithoutStudentDataInput;
  gender?: string | null;
  generalData?: GeneralDatumUpdateManyWithoutStudentDataInput;
  guid?: string | null;
  institutesId?: string | null;
  institutesName?: string | null;
  internships?: InternshipUpdateManyWithoutStudentDataInput;
  internshipsCds?: InternshipsCdUpdateManyWithoutStudentDataInput;
  internshipsIni?: InternshipsIniUpdateManyWithoutStudentDataInput;
  internshipsIsrms?: InternshipsIsrmUpdateManyWithoutStudentDataInput;
  interview?: InterviewUpdateManyWithoutStudentDataInput;
  ita?: ItaUpdateManyWithoutStudentDataInput;
  legacyRequirements?: LegacyRequirementUpdateManyWithoutStudentDataInput;
  mltSwitch?: boolean | null;
  notes?: NoteUpdateManyWithoutStudentDataInput;
  parttime?: number | null;
  practicum?: PracticumUpdateManyWithoutStudentDataInput;
  presentations?: PresentationUpdateManyWithoutStudentDataInput;
  program?: string | null;
  programStatus?: ProgramStatusUpdateManyWithoutStudentDataInput;
  projectTopic?: ProjectTopicUpdateManyWithoutStudentDataInput;
  qualsCommittee?: QualsCommitteeUpdateManyWithoutStudentDataInput;
  residency?: string | null;
  rotations?: RotationUpdateManyWithoutStudentDataInput;
  statements?: StatementUpdateManyWithoutStudentDataInput;
  status?: string | null;
  statusDate?: Date | null;
  studentAdvisors?: StudentAdvisorUpdateManyWithoutStudentDataInput;
  studentApps?: StudentAppUpdateManyWithoutStudentDataInput;
  studentDataHcii?: StudentDataHciiUpdateManyWithoutStudentDataInput;
  studentDataIni?: StudentDataIniUpdateManyWithoutStudentDataInput;
  studentDataMl?: StudentDataMlUpdateManyWithoutStudentDataInput;
  studentDataRi?: StudentDataRiWhereUniqueInput | null;
  studentFiles?: StudentFileUpdateManyWithoutStudentDataInput;
  studentInstitutes?: StudentInstituteUpdateManyWithoutStudentDataInput;
  studentMentors?: StudentMentorUpdateManyWithoutStudentDataInput;
  studentOverrides?: StudentOverrideUpdateManyWithoutStudentDataInput;
  studentPubs?: StudentPubUpdateManyWithoutStudentDataInput;
  studentResidency?: StudentResidencyUpdateManyWithoutStudentDataInput;
  studentSkills?: StudentSkillUpdateManyWithoutStudentDataInput;
  teachingReq?: TeachingReqUpdateManyWithoutStudentDataInput;
  thesisCommittee?: ThesisCommitteeUpdateManyWithoutStudentDataInput;
  thesisTopic?: ThesisTopicUpdateManyWithoutStudentDataInput;
  undergrad?: string | null;
  userRole?: UserRoleWhereUniqueInput | null;
  year?: number | null;
  yearAdjust?: string | null;
};
