import { Advisor } from "../advisor/Advisor";
import { Area } from "../area/Area";
import { Award } from "../award/Award";
import { CommitteeService } from "../committeeService/CommitteeService";
import { DegreeStatus } from "../degreeStatus/DegreeStatus";
import { Employment } from "../employment/Employment";
import { EvaluationLetter } from "../evaluationLetter/EvaluationLetter";
import { ExpNeuroReq } from "../expNeuroReq/ExpNeuroReq";
import { Fellowship } from "../fellowship/Fellowship";
import { Funding } from "../funding/Funding";
import { GeneralDatum } from "../generalDatum/GeneralDatum";
import { Internship } from "../internship/Internship";
import { InternshipsCd } from "../internshipsCd/InternshipsCd";
import { InternshipsIni } from "../internshipsIni/InternshipsIni";
import { InternshipsIsrm } from "../internshipsIsrm/InternshipsIsrm";
import { Interview } from "../interview/Interview";
import { Ita } from "../ita/Ita";
import { LegacyRequirement } from "../legacyRequirement/LegacyRequirement";
import { Note } from "../note/Note";
import { Practicum } from "../practicum/Practicum";
import { Presentation } from "../presentation/Presentation";
import { ProgramStatus } from "../programStatus/ProgramStatus";
import { ProjectTopic } from "../projectTopic/ProjectTopic";
import { QualsCommittee } from "../qualsCommittee/QualsCommittee";
import { Rotation } from "../rotation/Rotation";
import { Statement } from "../statement/Statement";
import { StudentAdvisor } from "../studentAdvisor/StudentAdvisor";
import { StudentApp } from "../studentApp/StudentApp";
import { StudentDataHcii } from "../studentDataHcii/StudentDataHcii";
import { StudentDataIni } from "../studentDataIni/StudentDataIni";
import { StudentDataMl } from "../studentDataMl/StudentDataMl";
import { StudentDataRi } from "../studentDataRi/StudentDataRi";
import { StudentFile } from "../studentFile/StudentFile";
import { StudentInstitute } from "../studentInstitute/StudentInstitute";
import { StudentMentor } from "../studentMentor/StudentMentor";
import { StudentOverride } from "../studentOverride/StudentOverride";
import { StudentPub } from "../studentPub/StudentPub";
import { StudentResidency } from "../studentResidency/StudentResidency";
import { StudentSkill } from "../studentSkill/StudentSkill";
import { TeachingReq } from "../teachingReq/TeachingReq";
import { ThesisCommittee } from "../thesisCommittee/ThesisCommittee";
import { ThesisTopic } from "../thesisTopic/ThesisTopic";
import { UserRole } from "../userRole/UserRole";

export type StudentDatum = {
  advisors?: Array<Advisor>;
  area: string | null;
  areas?: Array<Area>;
  awards?: Array<Award>;
  citizenship: string | null;
  committeeService?: Array<CommitteeService>;
  curriculum: string | null;
  degree: string | null;
  degreeStatus?: Array<DegreeStatus>;
  department: string | null;
  employment?: Array<Employment>;
  enterDate: Date | null;
  evaluationLetters?: Array<EvaluationLetter>;
  expNeuroReq?: Array<ExpNeuroReq>;
  fellowships?: Array<Fellowship>;
  funding?: Array<Funding>;
  gender: string | null;
  generalData?: Array<GeneralDatum>;
  guid: string | null;
  id: number;
  institutesId: string | null;
  institutesName: string | null;
  internships?: Array<Internship>;
  internshipsCds?: Array<InternshipsCd>;
  internshipsIni?: Array<InternshipsIni>;
  internshipsIsrms?: Array<InternshipsIsrm>;
  interview?: Array<Interview>;
  ita?: Array<Ita>;
  legacyRequirements?: Array<LegacyRequirement>;
  mltSwitch: boolean | null;
  notes?: Array<Note>;
  parttime: number | null;
  practicum?: Array<Practicum>;
  presentations?: Array<Presentation>;
  program: string | null;
  programStatus?: Array<ProgramStatus>;
  projectTopic?: Array<ProjectTopic>;
  qualsCommittee?: Array<QualsCommittee>;
  residency: string | null;
  rotations?: Array<Rotation>;
  statements?: Array<Statement>;
  status: string | null;
  statusDate: Date | null;
  studentAdvisors?: Array<StudentAdvisor>;
  studentApps?: Array<StudentApp>;
  studentDataHcii?: Array<StudentDataHcii>;
  studentDataIni?: Array<StudentDataIni>;
  studentDataMl?: Array<StudentDataMl>;
  studentDataRi?: StudentDataRi | null;
  studentFiles?: Array<StudentFile>;
  studentInstitutes?: Array<StudentInstitute>;
  studentMentors?: Array<StudentMentor>;
  studentOverrides?: Array<StudentOverride>;
  studentPubs?: Array<StudentPub>;
  studentResidency?: Array<StudentResidency>;
  studentSkills?: Array<StudentSkill>;
  teachingReq?: Array<TeachingReq>;
  thesisCommittee?: Array<ThesisCommittee>;
  thesisTopic?: Array<ThesisTopic>;
  undergrad: string | null;
  userRole?: UserRole | null;
  year: number | null;
  yearAdjust: string | null;
};
