/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ApplywebStudentMigrationDatum as PrismaApplywebStudentMigrationDatum,
} from "@prisma/client";

export class ApplywebStudentMigrationDatumServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ApplywebStudentMigrationDatumCountArgs, "select">
  ): Promise<number> {
    return this.prisma.applywebStudentMigrationDatum.count(args);
  }

  async applywebStudentMigrationData<
    T extends Prisma.ApplywebStudentMigrationDatumFindManyArgs
  >(
    args: Prisma.SelectSubset<
      T,
      Prisma.ApplywebStudentMigrationDatumFindManyArgs
    >
  ): Promise<PrismaApplywebStudentMigrationDatum[]> {
    return this.prisma.applywebStudentMigrationDatum.findMany<Prisma.ApplywebStudentMigrationDatumFindManyArgs>(
      args
    );
  }
  async applywebStudentMigrationDatum<
    T extends Prisma.ApplywebStudentMigrationDatumFindUniqueArgs
  >(
    args: Prisma.SelectSubset<
      T,
      Prisma.ApplywebStudentMigrationDatumFindUniqueArgs
    >
  ): Promise<PrismaApplywebStudentMigrationDatum | null> {
    return this.prisma.applywebStudentMigrationDatum.findUnique(args);
  }
  async createApplywebStudentMigrationDatum<
    T extends Prisma.ApplywebStudentMigrationDatumCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplywebStudentMigrationDatumCreateArgs>
  ): Promise<PrismaApplywebStudentMigrationDatum> {
    return this.prisma.applywebStudentMigrationDatum.create<T>(args);
  }
  async updateApplywebStudentMigrationDatum<
    T extends Prisma.ApplywebStudentMigrationDatumUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplywebStudentMigrationDatumUpdateArgs>
  ): Promise<PrismaApplywebStudentMigrationDatum> {
    return this.prisma.applywebStudentMigrationDatum.update<T>(args);
  }
  async deleteApplywebStudentMigrationDatum<
    T extends Prisma.ApplywebStudentMigrationDatumDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplywebStudentMigrationDatumDeleteArgs>
  ): Promise<PrismaApplywebStudentMigrationDatum> {
    return this.prisma.applywebStudentMigrationDatum.delete(args);
  }
}
