/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ReviewPeriodReference as PrismaReviewPeriodReference,
} from "@prisma/client";

export class ReviewPeriodReferenceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ReviewPeriodReferenceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.reviewPeriodReference.count(args);
  }

  async reviewPeriodReferences<
    T extends Prisma.ReviewPeriodReferenceFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ReviewPeriodReferenceFindManyArgs>
  ): Promise<PrismaReviewPeriodReference[]> {
    return this.prisma.reviewPeriodReference.findMany<Prisma.ReviewPeriodReferenceFindManyArgs>(
      args
    );
  }
  async reviewPeriodReference<
    T extends Prisma.ReviewPeriodReferenceFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ReviewPeriodReferenceFindUniqueArgs>
  ): Promise<PrismaReviewPeriodReference | null> {
    return this.prisma.reviewPeriodReference.findUnique(args);
  }
  async createReviewPeriodReference<
    T extends Prisma.ReviewPeriodReferenceCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ReviewPeriodReferenceCreateArgs>
  ): Promise<PrismaReviewPeriodReference> {
    return this.prisma.reviewPeriodReference.create<T>(args);
  }
  async updateReviewPeriodReference<
    T extends Prisma.ReviewPeriodReferenceUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ReviewPeriodReferenceUpdateArgs>
  ): Promise<PrismaReviewPeriodReference> {
    return this.prisma.reviewPeriodReference.update<T>(args);
  }
  async deleteReviewPeriodReference<
    T extends Prisma.ReviewPeriodReferenceDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ReviewPeriodReferenceDeleteArgs>
  ): Promise<PrismaReviewPeriodReference> {
    return this.prisma.reviewPeriodReference.delete(args);
  }
}
