/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntFilter } from "../../util/IntFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { QualsResearchListRelationFilter } from "../../qualsResearch/base/QualsResearchListRelationFilter";
import { QualsResearchForOtherStudentListRelationFilter } from "../../qualsResearchForOtherStudent/base/QualsResearchForOtherStudentListRelationFilter";
import { QualsWritingListRelationFilter } from "../../qualsWriting/base/QualsWritingListRelationFilter";
import { StudentDatumWhereUniqueInput } from "../../studentDatum/base/StudentDatumWhereUniqueInput";

@InputType()
class QualsCommitteeWhereInput {
  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  memberType?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  overrideResearch?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  overrideSpeaking?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  overrideWriting?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => QualsResearchListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QualsResearchListRelationFilter)
  @IsOptional()
  @Field(() => QualsResearchListRelationFilter, {
    nullable: true,
  })
  qualsResearch?: QualsResearchListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => QualsResearchForOtherStudentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QualsResearchForOtherStudentListRelationFilter)
  @IsOptional()
  @Field(() => QualsResearchForOtherStudentListRelationFilter, {
    nullable: true,
  })
  qualsResearchForOtherStudent?: QualsResearchForOtherStudentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => QualsWritingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QualsWritingListRelationFilter)
  @IsOptional()
  @Field(() => QualsWritingListRelationFilter, {
    nullable: true,
  })
  qualsWriting?: QualsWritingListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => StudentDatumWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => StudentDatumWhereUniqueInput)
  @IsOptional()
  @Field(() => StudentDatumWhereUniqueInput, {
    nullable: true,
  })
  studentData?: StudentDatumWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  urId?: IntFilter;
}

export { QualsCommitteeWhereInput as QualsCommitteeWhereInput };
