/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumQualsResearchApproach } from "./EnumQualsResearchApproach";
import {
  IsEnum,
  IsOptional,
  IsString,
  ValidateNested,
  IsInt,
} from "class-validator";
import { EnumQualsResearchInsight } from "./EnumQualsResearchInsight";
import { EnumQualsResearchInterpretation } from "./EnumQualsResearchInterpretation";
import { EnumQualsResearchOverall } from "./EnumQualsResearchOverall";
import { QualsCommitteeWhereUniqueInput } from "../../qualsCommittee/base/QualsCommitteeWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumQualsResearchStatus } from "./EnumQualsResearchStatus";
import { EnumQualsResearchUnderstanding } from "./EnumQualsResearchUnderstanding";

@InputType()
class QualsResearchUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumQualsResearchApproach,
  })
  @IsEnum(EnumQualsResearchApproach)
  @IsOptional()
  @Field(() => EnumQualsResearchApproach, {
    nullable: true,
  })
  approach?: "Excellent" | "Good" | "Satisfactory" | "Unsatisfactory" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  approachExp?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumQualsResearchInsight,
  })
  @IsEnum(EnumQualsResearchInsight)
  @IsOptional()
  @Field(() => EnumQualsResearchInsight, {
    nullable: true,
  })
  insight?: "Excellent" | "Good" | "Satisfactory" | "Unsatisfactory" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  insightExp?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumQualsResearchInterpretation,
  })
  @IsEnum(EnumQualsResearchInterpretation)
  @IsOptional()
  @Field(() => EnumQualsResearchInterpretation, {
    nullable: true,
  })
  interpretation?:
    | "Excellent"
    | "Good"
    | "Satisfactory"
    | "Unsatisfactory"
    | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  interpretationExp?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumQualsResearchOverall,
  })
  @IsEnum(EnumQualsResearchOverall)
  @IsOptional()
  @Field(() => EnumQualsResearchOverall, {
    nullable: true,
  })
  overall?: "Excellent" | "Good" | "Satisfactory" | "Unsatisfactory" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  overallExp?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  progress?: string | null;

  @ApiProperty({
    required: false,
    type: () => QualsCommitteeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => QualsCommitteeWhereUniqueInput)
  @IsOptional()
  @Field(() => QualsCommitteeWhereUniqueInput, {
    nullable: true,
  })
  qualsCommittee?: QualsCommitteeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumQualsResearchStatus,
  })
  @IsEnum(EnumQualsResearchStatus)
  @IsOptional()
  @Field(() => EnumQualsResearchStatus, {
    nullable: true,
  })
  status?: "Satisfied" | "Progress" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  studentId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  summary?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumQualsResearchUnderstanding,
  })
  @IsEnum(EnumQualsResearchUnderstanding)
  @IsOptional()
  @Field(() => EnumQualsResearchUnderstanding, {
    nullable: true,
  })
  understanding?:
    | "Excellent"
    | "Good"
    | "Satisfactory"
    | "Unsatisfactory"
    | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  understandingExp?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  urId?: number | null;
}

export { QualsResearchUpdateInput as QualsResearchUpdateInput };
